#!/bin/bash
set -exuo pipefail

declare -r BDEPS=(
    curl
)

declare -r DEPS=(
php-gd
php-cli
php-curl
php-mbstring
php-xml 
php-mysqli
mariadb-client-10.3
)

apt-get install "${BDEPS[@]}" "${DEPS[@]}"


declare -r ASC_URL="https://builds.piwik.org/matomo-${PRODUCT_VERSION}.tar.gz.asc" # 3.9.8
declare -r URL="https://builds.piwik.org/matomo-3.11.0.tar.gz"
curl -o matomo.tar.gz -SL "${URL}"
# todo - verify asc signature with gnupg

tar xzvf matomo.tar.gz
rm 'How to install Matomo.html'
rm matomo.tar.gz
cd matomo/

tar czf matomo.tar.gz *

mv matomo.tar.gz "${SRCDIR}"
chown www-data:www-data "${SRCDIR}/matomo.tar.gz"

apt-get purge "${BDEPS[@]}"
